version: '3.8'
services:
  mysql:
    image: mysql:5.7
    container_name: mysql
    environment:
      MYSQL_ROOT_PASSWORD: secet
      # MYSQL_DATABASE: mydatabase
      # MYSQL_USER: user
      # MYSQL_PASSWORD: secet
    ports:
      - "3306:3306"
    networks:
      - my-network
    volumes:
      - db_data:/var/lib/mysql
      - ./init:/docker-entrypoint-initdb.d  # MySQL 생성 시 쿼리문 연결
    healthcheck:
      test: ["CMD-SHELL", "mysqladmin ping -h localhost -u root --password=secet && mysql -u root --password=secet -e 'SELECT 1;'"]
      interval: 10s
      timeout: 30s
      retries: 5

  backend:
    build:
      context: ./internet-banking-server
    ports:
      - "30000:30000"
    depends_on:
      mysql:
        condition: service_healthy
    env_file: 
      - ./internet-banking-server/.env
    networks:
      - my-network
         

  frontend:
    build:
      context: ./internet-banking-client
    command: npm run dev -- --host 0.0.0.0
    ports:
      - "8080:5173"
    networks:
      - my-network

volumes:
  db_data:

networks:
  my-network:
    driver: bridge
